import Head from "next/head";

export default function Home() {

  const url = `https://api.openweathermap.org/data/2.5/weather?q={baltimore}&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  return (
    <>
      <Head>
        <title>Weather - App</title>
        <meta name="description" content="Generated by next app" />
      </Head>
      <h1>Yo</h1>
    </>
  );
};
